config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'my_cosplays', to: 'cosplays#my_cosplays'
  resources :cosplays do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:destroy, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :cosplay

end

app/models/cosplay.rb
class Cosplay < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cosplays
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_booking, only: :destroy
  before_action :set_cosplay, only: [:new, :create]
  def index
    @bookings = Booking.where(user: current_user)
  end

  def new
    @cosplay = Cosplay.find(params[:cosplay_id])
    @booking = Booking.new
  end

  def create
    @user = current_user
    @booking = Booking.new(booking_params)
    @booking.cosplay = @cosplay
    @booking.user = @user
    if @booking.save
      redirect_to bookings_path
    else
      @cosplay = Cosplay.new
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:cosplay_id, :starting_date, :ending_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_cosplay
    @cosplay = Cosplay.find(params[:cosplay_id])
  end
end

app/controllers/cosplays_controller.rb
class CosplaysController < ApplicationController
  def index
    if params[:query].present?
      @cosplays = Cosplay.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @cosplays = Cosplay.all
    end
  end

  def new
    @cosplay = Cosplay.new
  end

  def create
    @cosplay = Cosplay.new(cosplay_params)
    if @cosplay.save
      redirect_to cosplays_path(@cosplay)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @cosplay = Cosplay.find(params[:id])
  end

  def destroy
    @cosplay = Cosplay.find(params[:id])
    @cosplay.destroy
    redirect_to cosplays_path, status: :see_other
  end

  def edit
    @cosplay = Cosplay.find(params[:id])
  end

  def update
    @cosplay = Cosplay.find(params[:id])
    @cosplay.update(cosplay_params)
    redirect_to cosplays_path(@cosplay)
  end

  def my_cosplays
    @my_cosplays = Cosplay.where(user: current_user)
  end

  private

  def set_list
    @cosplay = Cosplay.find(params[:id])
  end

  def cosplay_params
    params.require(:cosplay).permit(:name, :price, :category, :size, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
booking list
<div class="container ">

  <% @bookings.each do |booking| %>
<div class="card-product d-flex">
    <%= cl_image_tag booking.cosplay.photo.key,class:'cosplay_image'%>
    <div class="card-product-infos d-flex justify-content-around w-100">
      <h2><%= booking.cosplay.name %></h2>
      <p><%= booking.starting_date %> <%= booking.ending_date %></p>
      <%= link_to "Delete", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary"  %>
    </div>
</div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container">
   Welcome to booking page
 <%= simple_form_for ([@cosplay, @booking]) do |f| %>
   <%= f.input :starting_date, as: :date, html5: true%>
   <%= f.input :ending_date, as: :date, html5: true%>
   <%= f.submit class: 'btn waves-effect waves-light' %>
 <% end %>
</div>

app/views/cosplays/edit.html.erb
<h3>Update your Cosplay</h3>
<%= simple_form_for @cosplay do |f| %>
  <%= f.input :name %>
  <%= f.input :category, collection: ["Anime", "Films", "Halloween", "Games"] %>
  <%= f.input :price %>
  <%= f.input :size, collection: ["Small", "Medium", "Large", "X-Large", "2XL"] %>
  <%= f.input :photos, as: :file, input_html: { multiple: true }  %>
  <%= f.button :submit %>
<% end %>

app/views/cosplays/index.html.erb
 <div class="container">
  <div class="cards">
    <% @cosplays.each do |cosplay| %>
      <div class="card card-grid">
      <div class="cosplay-image">
        <%= cl_image_tag cosplay.photo.key %>
      </div>
        <div class="card-body">
          <h4 class="card-title"><%= cosplay.name  %></h4>
          <p class="card-text"> Rs<%= cosplay.price%></p>
          <p class="card-text"><%= cosplay.category  %></p>
          <%= link_to "Show More", cosplay_path(cosplay), class: "btn btn-primary"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cosplays/my_cosplays.html.erb
 <h1>My Cosplays</h1>

<div class="container">
  <div class="cards">
    <% @my_cosplays.each do |cosplay| %>
      <div class="card card-grid">
      <div class="cosplay-image">
        <%= cl_image_tag cosplay.photo.key %>
      </div>
        <div class="card-body">
          <h4 class="card-title"><%= cosplay.name  %></h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cosplays/new.html.erb
<div class="container">
 <h3>Create a new Cosplay</h3>
 <%= simple_form_for @cosplay do |f| %>
   <%= f.input :name %>
   <%= f.input :category, collection: ["Anime", "Films", "Halloween", "Games","Cartoon"] %>
   <%= f.input :price %>
   <%= f.input :size, collection: ["Small", "Medium", "Large", "X-Large", "2XL"] %>
   <%= f.input :photos, as: :file, input_html: { multiple: true }  %>
   <%= f.button :submit %>
 <% end %>
</div>

app/views/cosplays/show.html.erb
<div class="card-products">
  <div>
    <%= cl_image_tag @cosplay.photo.key,class:'cosplay_image'%>

  </div>

  <div class="card-product-infos">
    <ul><%=@cosplay.name%>
      <li><%=@cosplay.size%></li>
      <li><%=@cosplay.category%></li>
      <li><%=@cosplay.price%></li>
    </ul>
  </div>
  <div class="btn_cos">
    <%= link_to "Delete cosplay",cosplay_path(@cosplay),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary" %>
    <%= link_to "Update Cosplay", edit_cosplay_path(@cosplay), class: "btn btn-primary" %>
    <%= link_to "book cosplay", new_cosplay_booking_path(@cosplay), class: "btn btn-primary" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CosMauPlay</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <div class="nav-block"></div>
    <div class="layout">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="d-flex flex-column allign-items-center ">
  <h1 class="animate-charcter">
    CosMauPlay
  </h1>
</div>
<div id="carouselExampleControlsNoTouching" class="carousel slide" data-bs-touch="false" data-bs-interval="false">
  <div class="carousel-inner">
    <div class="carousel-item active">
     <%# <a class="btn btn-secondary btn-lg button-cosplay" href= "/cosplays" >Display Cosplays</a> %>
      <img src="https://images.unsplash.com/photo-1605663839223-7fe37a3755a5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=653&q=80" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <%# <a class="btn btn-secondary btn-lg button-cosplay" href= "/cosplays" >Display Cosplays</a> %>
      <img src="https://www.animegastore.com/mobile/images/shop/jujutsukaisen/jj011.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
     <%# <a class="btn btn-secondary btn-lg button-cosplay" href= "/cosplays" >Display Cosplays</a> %>
      <img src="https://images.unsplash.com/photo-1642456074142-92f75cb84533?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80" class="d-block w-100" alt="...">
    </div>
     <div class="carousel-item">
     <%# <a class="btn btn-secondary btn-lg button-cosplay" href= "/cosplays" >Display Cosplays</a> %>
      <img src="https://www.belloflostsouls.net/wp-content/uploads/2020/11/117769261_3271558252920934_8354773004161752511_o-1-e1605887750913.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControlsNoTouching" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControlsNoTouching" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_banner.html.erb
<%#
<%=
 <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://img.freepik.com/free-vector/young-man-various-fighter-costume-with-weapon-cartoon-style-graphic-designer-ninja-vector-illustration_1150-61254.jpg?w=900&t=st=1665577336~exp=1665577936~hmac=a26dc675d8f8afc2391963a6edf0e4e5b8764d6c3b6e08a6a135aab9b685af16);">
  <div class="container">
    <h1>
     <strong>WElCOME TO COSPLAY WORLD</strong>!
    </h1>

  </div>
</div>
%

app/views/shared/_footer.html.erb
<div class="footer">
 <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
   </div>
    <div class="footer-text">
      Connect to our social media
      <p> website design by Ashley, Komal, Cedric and Ameenah</p>
    </div>
  </div>
</div>

app/views/shared/_form.html.erb
<%= simple_form_for(article) do |f| %>
  <%= f.input :photo, as: :file %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid nav">
      <div class="search-form-control form-group">
         <%= form_with url: cosplays_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a cosplay"
          %>
           <%= submit_tag "Search", class: "btn btn-primary btn-sm btn-search"  %>
        <% end %>
      </div>
    <%= link_to "#", class: "navbar-brand logo-icon" do %>
      <%= image_tag "https://images.assetsdelivery.com/compings_v2/doublerdesign/doublerdesign2111/doublerdesign211100139.jpg" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get">

      </form>
    </div>

     <ul class="navbar-nav me-auto">
        <%= link_to "Home", "/", class: "nav-link button-nav" %>
        <%= link_to "Cosplays", "/cosplays", class: "nav-link button-nav" %>
        <% if user_signed_in? %>
          <li class="nav-item active"> </li>
          <li class="nav-item"></li>
          <li class="nav-item dropdown">
            <%= image_tag "https://avatars.githubusercontent.com/u/112051440?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Loan a Cosplay", "/cosplays/new", class: "dropdown-item" %>
              <%= link_to "My booking", "/bookings", class: "dropdown-item" %>
              <%= link_to "My Cosplay", "/my_cosplays", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link button-nav" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>